language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt -r requirements_test.txt cython --use-mirrors; python setup.py build_ext --inplace --force
# command to run tests, e.g. python setup.py test
script:  py.test -k "-TestServerGen and -TestMCR and -testNBTSpeed"
